# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 08:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunSQL([("""
            CREATE SERVER me FOREIGN DATA WRAPPER postgres_fdw OPTIONS (dbname 'fdwfunhouse');
            CREATE USER MAPPING FOR current_user SERVER me OPTIONS (user 'postgres');
            CREATE FOREIGN TABLE foreign_auth_user (
                id integer NOT NULL,
                password character varying(128) NOT NULL,
                last_login timestamp with time zone,
                is_superuser boolean NOT NULL,
                username character varying(150) NOT NULL,
                first_name character varying(30) NOT NULL,
                last_name character varying(30) NOT NULL,
                email character varying(254) NOT NULL,
                is_staff boolean NOT NULL,
                is_active boolean NOT NULL,
                date_joined timestamp with time zone NOT NULL
            )
            SERVER me
            OPTIONS (
                schema_name 'public',
                table_name 'auth_user'
            );
        """)])
    ]
